### ISSUE TITLE
Support Result#swap

### ISSUE THREAD

**Issue by dzikoysk** [panda-lang/expressible#11]
`Result<V, E>.swap() -> Result<E, V>`

**Comment by sgaurav37533** [comment]
Hi I can work on this please assign me this issue.

**Comment by dzikoysk** [comment]
Thanks :) It's not a priority for me now, so feel free to contribute after 01.10 when Hacktoberfest starts

**Comment by dzikoysk** [comment]
I somehow need this feature, are you still interested in this PR @sgaurav37533? :)
